services:
  node-dev:
    build:
      context: .
      target: typingjerboa-node-dev
    image: typingjerboa-node-dev
    volumes:
      - ./src:/app/src
    environment:
      - HI=HI
    ports:
      - "3000:3000"

  node-prod:
    build:
      context: .
      target: typingjerboa-node-prod
    image: typingjerboa-node-prod
    environment:
      - HI=HI
    ports:
      - "3000:80"
  
  postgres-dev:
    build:
      context: .
      target: typingjerboa-postgres-dev
    image: typingjerboa-postgres-dev
    volumes:
      - /var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "2345:5432"

  postgres-prod:
    build:
      context: .
      target: typingjerboa-postgres-prod
    image: typingjerboa-postgres-prod
    volumes:
      - /var/lib/postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"