export const LanguageScripts = {
  CYRILLIC_RUSSIAN: "cyrillic-russian",
  LATIN_ENGLISH: "latin-english"
} as const;

export type Rows = {
  homerow: string[][],
  upperrow: string[][],
  lowerrow: string[][],
  symbolrow: string[][]
};

export type ManualKeyboardMapping = {
  letters: Rows,
  capitals: Rows,
  numbers: Rows,
  symbols: Rows
};

export const ManualKeyboardMap: {[key: string]: ManualKeyboardMapping} = {
  [LanguageScripts.LATIN_ENGLISH]: {
    letters: {
      homerow: [["d", "f", "j", "k"], ["a", "s", "l"], ["g", "h"]],
      upperrow: [["e", "r"], ["u", "i"], ["q", "w"], ["o", "p"], ["t", "y"]],
      lowerrow: [["c", "v"], ["m"], ["z", "x"], ["b", "n"]],
      symbolrow: []
    },
    capitals: {
      homerow: [["D", "F", "J", "K"], ["A", "S", "L"], ["G", "H"]],
      upperrow: [["E", "R"], ["U", "I"], ["Q", "W"], ["O", "P"], ["T", "Y"]],
      lowerrow: [["C", "V"], ["M"], ["Z", "X"], ["B", "N"]],
      symbolrow: []
    },
    numbers: {
      homerow: [],
      upperrow: [],
      lowerrow: [],
      symbolrow: [["1", "2", "3", "4"], ["5", "6", "7"], ["8", "9", "0"]]
    },
    symbols: {
      homerow: [[";", "'"], [":", "\""]],
      upperrow: [["[", "]", "\\"], ["{", "}", "|"]],
      lowerrow: [[",", ".", "/"], ["<", ">", "?"]],
      symbolrow: [["!", "@", "#"], ["$", "%", "^"], ["&", "*", "(", ")"], ["-", "="], ["_", "+"], ["`", "~"]]
    }
  },
  [LanguageScripts.CYRILLIC_RUSSIAN]: {
    letters: {
      homerow: [["в", "а", "о", "л"], ["ф", "ы"], ["д", "ж", "э"], ["п", "р"]],
      upperrow: [["у", "к"], ["г", "ш"], ["й", "ц"], ["щ", "з"], ["е", "н"], ["х", "ъ"]],
      lowerrow: [["с", "м"], ["ь", "б", "ю"], ["я", "ч"], ["и", "т"]],
      symbolrow: [["ё"]]
    },
    capitals: {
      homerow: [["В", "А", "О", "Л"], ["Ф", "Ы"], ["Д", "Ж", "Э"], ["П", "Р"]],
      upperrow: [["У", "К"], ["Г", "Ш"], ["Й", "Ц"], ["Щ", "З"], ["Е", "Н"], ["Х", "Ъ"]],
      lowerrow: [["С", "М"], ["Ь", "Б", "Ю"], ["Я", "Ч"], ["И", "Т"]],
      symbolrow: [["Ё"]]
    },
    numbers: {
      homerow: [],
      upperrow: [],
      lowerrow: [],
      symbolrow: [["1", "2", "3", "4"], ["5", "6", "7"], ["8", "9", "0"]]
    },
    symbols: {
      homerow: [],
      upperrow: [["\\", "/"]],
      lowerrow: [[".", ","]],
      symbolrow: [["!", "\"", "№"], [";", "%", ":"], ["?", "*", "(", ")"], ["_", "+"]]
    }
  }
};

// export const LearningTypes = {
//   LETTER: "letter",
//   CAPITAL: "capital",
//   NUMBER: "number",
//   SYMBOL: "symbol"
// } as const;

// export type LearnableCharacter = {
//   char: string,
//   type: (typeof LearningTypes)[keyof typeof LearningTypes]
// };

// export type KeyboardMapping = {
//   '`': LearnableCharacter,
//   '1': LearnableCharacter,
//   '2': LearnableCharacter,
//   '3': LearnableCharacter,
//   '4': LearnableCharacter,
//   '5': LearnableCharacter,
//   '6': LearnableCharacter,
//   '7': LearnableCharacter,
//   '8': LearnableCharacter,
//   '9': LearnableCharacter,
//   '0': LearnableCharacter,
//   '-': LearnableCharacter,
//   '=': LearnableCharacter,
//   'q': LearnableCharacter,
//   'w': LearnableCharacter,
//   'e': LearnableCharacter,
//   'r': LearnableCharacter,
//   't': LearnableCharacter,
//   'y': LearnableCharacter,
//   'u': LearnableCharacter,
//   'i': LearnableCharacter,
//   'o': LearnableCharacter,
//   'p': LearnableCharacter,
//   '[': LearnableCharacter,
//   ']': LearnableCharacter,
//   '\\': LearnableCharacter,
//   'a': LearnableCharacter,
//   's': LearnableCharacter,
//   'd': LearnableCharacter,
//   'f': LearnableCharacter,
//   'g': LearnableCharacter,
//   'h': LearnableCharacter,
//   'j': LearnableCharacter,
//   'k': LearnableCharacter,
//   'l': LearnableCharacter,
//   ';': LearnableCharacter,
//   '\'': LearnableCharacter,
//   'z': LearnableCharacter,
//   'x': LearnableCharacter,
//   'c': LearnableCharacter,
//   'v': LearnableCharacter,
//   'b': LearnableCharacter,
//   'n': LearnableCharacter,
//   'm': LearnableCharacter,
//   ',': LearnableCharacter,
//   '.': LearnableCharacter,
//   '/': LearnableCharacter,
//   '~': LearnableCharacter,
//   '!': LearnableCharacter,
//   '@': LearnableCharacter,
//   '#': LearnableCharacter,
//   '$': LearnableCharacter,
//   '%': LearnableCharacter,
//   '^': LearnableCharacter,
//   '&': LearnableCharacter,
//   '*': LearnableCharacter,
//   '(': LearnableCharacter,
//   ')': LearnableCharacter,
//   '_': LearnableCharacter,
//   '+': LearnableCharacter,
//   'Q': LearnableCharacter,
//   'W': LearnableCharacter,
//   'E': LearnableCharacter,
//   'R': LearnableCharacter,
//   'T': LearnableCharacter,
//   'Y': LearnableCharacter,
//   'U': LearnableCharacter,
//   'I': LearnableCharacter,
//   'O': LearnableCharacter,
//   'P': LearnableCharacter,
//   '{': LearnableCharacter,
//   '}': LearnableCharacter,
//   '|': LearnableCharacter,
//   'A': LearnableCharacter,
//   'S': LearnableCharacter,
//   'D': LearnableCharacter,
//   'F': LearnableCharacter,
//   'G': LearnableCharacter,
//   'H': LearnableCharacter,
//   'J': LearnableCharacter,
//   'K': LearnableCharacter,
//   'L': LearnableCharacter,
//   ':': LearnableCharacter,
//   '"': LearnableCharacter,
//   'Z': LearnableCharacter,
//   'X': LearnableCharacter,
//   'C': LearnableCharacter,
//   'V': LearnableCharacter,
//   'B': LearnableCharacter,
//   'N': LearnableCharacter,
//   'M': LearnableCharacter,
//   '<': LearnableCharacter,
//   '>': LearnableCharacter,
//   '?': LearnableCharacter
// };

// export const KeyboardMap: {[key: string]: KeyboardMapping} = {
//   [LanguageScripts.LATIN_ENGLISH]: {
//     '`': {char:'`', type: LearningTypes.LETTER},
//     '1': {char:'1', type: LearningTypes.LETTER},
//     '2': {char:'2', type: LearningTypes.LETTER},
//     '3': {char:'3', type: LearningTypes.LETTER},
//     '4': {char:'4', type: LearningTypes.LETTER},
//     '5': {char:'5', type: LearningTypes.LETTER},
//     '6': {char:'6', type: LearningTypes.LETTER},
//     '7': {char:'7', type: LearningTypes.LETTER},
//     '8': {char:'8', type: LearningTypes.LETTER},
//     '9': {char:'9', type: LearningTypes.LETTER},
//     '0': {char:'0', type: LearningTypes.LETTER},
//     '-': {char:'-', type: LearningTypes.LETTER},
//     '=': {char:'=', type: LearningTypes.LETTER},
//     'q': {char:'q', type: LearningTypes.LETTER},
//     'w': {char:'w', type: LearningTypes.LETTER},
//     'e': {char:'e', type: LearningTypes.LETTER},
//     'r': {char:'r', type: LearningTypes.LETTER},
//     't': {char:'t', type: LearningTypes.LETTER},
//     'y': {char:'y', type: LearningTypes.LETTER},
//     'u': {char:'u', type: LearningTypes.LETTER},
//     'i': {char:'i', type: LearningTypes.LETTER},
//     'o': {char:'o', type: LearningTypes.LETTER},
//     'p': {char:'p', type: LearningTypes.LETTER},
//     '[': {char:'[', type: LearningTypes.LETTER},
//     ']': {char:']', type: LearningTypes.LETTER},
//     '\\': {char:'\\', type: LearningTypes.LETTER},
//     'a': {char:'a', type: LearningTypes.LETTER},
//     's': {char:'s', type: LearningTypes.LETTER},
//     'd': {char:'d', type: LearningTypes.LETTER},
//     'f': {char:'f', type: LearningTypes.LETTER},
//     'g': {char:'g', type: LearningTypes.LETTER},
//     'h': {char:'h', type: LearningTypes.LETTER},
//     'j': {char:'j', type: LearningTypes.LETTER},
//     'k': {char:'k', type: LearningTypes.LETTER},
//     'l': {char:'l', type: LearningTypes.LETTER},
//     ';': {char:';', type: LearningTypes.LETTER},
//     '\'': {char:'\'', type: LearningTypes.LETTER},
//     'z': {char:'z', type: LearningTypes.LETTER},
//     'x': {char:'x', type: LearningTypes.LETTER},
//     'c': {char:'c', type: LearningTypes.LETTER},
//     'v': {char:'v', type: LearningTypes.LETTER},
//     'b': {char:'b', type: LearningTypes.LETTER},
//     'n': {char:'n', type: LearningTypes.LETTER},
//     'm': {char:'m', type: LearningTypes.LETTER},
//     ',': {char:',', type: LearningTypes.LETTER},
//     '.': {char:'.', type: LearningTypes.LETTER},
//     '/': {char:'/', type: LearningTypes.LETTER},
//     '~': {char:'~', type: LearningTypes.LETTER},
//     '!': {char:'!', type: LearningTypes.LETTER},
//     '@': {char:'@', type: LearningTypes.LETTER},
//     '#': {char:'#', type: LearningTypes.LETTER},
//     '$': {char:'$', type: LearningTypes.LETTER},
//     '%': {char:'%', type: LearningTypes.LETTER},
//     '^': {char:'^', type: LearningTypes.LETTER},
//     '&': {char:'&', type: LearningTypes.LETTER},
//     '*': {char:'*', type: LearningTypes.LETTER},
//     '(': {char:'(', type: LearningTypes.LETTER},
//     ')': {char:')', type: LearningTypes.LETTER},
//     '_': {char:'_', type: LearningTypes.LETTER},
//     '+': {char:'+', type: LearningTypes.LETTER},
//     'Q': {char:'Q', type: LearningTypes.LETTER},
//     'W': {char:'W', type: LearningTypes.LETTER},
//     'E': {char:'E', type: LearningTypes.LETTER},
//     'R': {char:'R', type: LearningTypes.LETTER},
//     'T': {char:'T', type: LearningTypes.LETTER},
//     'Y': {char:'Y', type: LearningTypes.LETTER},
//     'U': {char:'U', type: LearningTypes.LETTER},
//     'I': {char:'I', type: LearningTypes.LETTER},
//     'O': {char:'O', type: LearningTypes.LETTER},
//     'P': {char:'P', type: LearningTypes.LETTER},
//     '{': {char:'{', type: LearningTypes.LETTER},
//     '}': {char:'}', type: LearningTypes.LETTER},
//     '|': {char:'|', type: LearningTypes.LETTER},
//     'A': {char:'A', type: LearningTypes.LETTER},
//     'S': {char:'S', type: LearningTypes.LETTER},
//     'D': {char:'D', type: LearningTypes.LETTER},
//     'F': {char:'F', type: LearningTypes.LETTER},
//     'G': {char:'G', type: LearningTypes.LETTER},
//     'H': {char:'H', type: LearningTypes.LETTER},
//     'J': {char:'J', type: LearningTypes.LETTER},
//     'K': {char:'K', type: LearningTypes.LETTER},
//     'L': {char:'L', type: LearningTypes.LETTER},
//     ':': {char:':', type: LearningTypes.LETTER},
//     '"': {char:'"', type: LearningTypes.LETTER},
//     'Z': {char:'Z', type: LearningTypes.LETTER},
//     'X': {char:'X', type: LearningTypes.LETTER},
//     'C': {char:'C', type: LearningTypes.LETTER},
//     'V': {char:'V', type: LearningTypes.LETTER},
//     'B': {char:'B', type: LearningTypes.LETTER},
//     'N': {char:'N', type: LearningTypes.LETTER},
//     'M': {char:'M', type: LearningTypes.LETTER},
//     '<': {char:'<', type: LearningTypes.LETTER},
//     '>': {char:'>', type: LearningTypes.LETTER},
//     '?': {char:'?', type: LearningTypes.LETTER}
//   },
//   [LanguageScripts.CYRILLIC_RUSSIAN]: {
//     '`': {char: 'ё', type: LearningTypes.LETTER},
//     '1': {char: '1', type: LearningTypes.NUMBER},
//     '2': {char: '2', type: LearningTypes.NUMBER},
//     '3': {char: '3', type: LearningTypes.NUMBER},
//     '4': {char: '4', type: LearningTypes.NUMBER},
//     '5': {char: '5', type: LearningTypes.NUMBER},
//     '6': {char: '6', type: LearningTypes.NUMBER},
//     '7': {char: '7', type: LearningTypes.NUMBER},
//     '8': {char: '8', type: LearningTypes.NUMBER},
//     '9': {char: '9', type: LearningTypes.NUMBER},
//     '0': {char: '0', type: LearningTypes.NUMBER},
//     '-': {char: '-', type: LearningTypes.SYMBOL},
//     '=': {char: '=', type: LearningTypes.SYMBOL},
//     'q': {char: 'й', type: LearningTypes.LETTER},
//     'w': {char: 'ц', type: LearningTypes.LETTER},
//     'e': {char: 'у', type: LearningTypes.LETTER},
//     'r': {char: 'к', type: LearningTypes.LETTER},
//     't': {char: 'е', type: LearningTypes.LETTER},
//     'y': {char: 'н', type: LearningTypes.LETTER},
//     'u': {char: 'г', type: LearningTypes.LETTER},
//     'i': {char: 'ш', type: LearningTypes.LETTER},
//     'o': {char: 'щ', type: LearningTypes.LETTER},
//     'p': {char: 'з', type: LearningTypes.LETTER},
//     '[': {char: 'х', type: LearningTypes.LETTER},
//     ']': {char: 'ъ', type: LearningTypes.LETTER},
//     '\\': {char: '\\', type: LearningTypes.SYMBOL},
//     'a': {char: 'ф', type: LearningTypes.LETTER},
//     's': {char: 'ы', type: LearningTypes.LETTER},
//     'd': {char: 'в', type: LearningTypes.LETTER},
//     'f': {char: 'а', type: LearningTypes.LETTER},
//     'g': {char: 'п', type: LearningTypes.LETTER},
//     'h': {char: 'р', type: LearningTypes.LETTER},
//     'j': {char: 'о', type: LearningTypes.LETTER},
//     'k': {char: 'л', type: LearningTypes.LETTER},
//     'l': {char: 'д', type: LearningTypes.LETTER},
//     ';': {char: 'ж', type: LearningTypes.LETTER},
//     '\'': {char: 'э', type: LearningTypes.LETTER},
//     'z': {char: 'я', type: LearningTypes.LETTER},
//     'x': {char: 'ч', type: LearningTypes.LETTER},
//     'c': {char: 'с', type: LearningTypes.LETTER},
//     'v': {char: 'м', type: LearningTypes.LETTER},
//     'b': {char: 'и', type: LearningTypes.LETTER},
//     'n': {char: 'т', type: LearningTypes.LETTER},
//     'm': {char: 'ь', type: LearningTypes.LETTER},
//     ',': {char: 'б', type: LearningTypes.LETTER},
//     '.': {char: 'ю', type: LearningTypes.LETTER},
//     '/': {char: '.', type: LearningTypes.SYMBOL},
//     '~': {char: 'Ё', type: LearningTypes.LETTER},
//     '!': {char: '!', type: LearningTypes.SYMBOL},
//     '@': {char: '"', type: LearningTypes.SYMBOL},
//     '#': {char: '№', type: LearningTypes.SYMBOL},
//     '$': {char: ';', type: LearningTypes.SYMBOL},
//     '%': {char: '%', type: LearningTypes.SYMBOL},
//     '^': {char: ':', type: LearningTypes.SYMBOL},
//     '&': {char: '?', type: LearningTypes.SYMBOL},
//     '*': {char: '*', type: LearningTypes.SYMBOL},
//     '(': {char: '(', type: LearningTypes.SYMBOL},
//     ')': {char: ')', type: LearningTypes.SYMBOL},
//     '_': {char: '_', type: LearningTypes.SYMBOL},
//     '+': {char: '+', type: LearningTypes.SYMBOL},
//     'Q': {char: 'Й', type: LearningTypes.LETTER},
//     'W': {char: 'Ц', type: LearningTypes.LETTER},
//     'E': {char: 'У', type: LearningTypes.LETTER},
//     'R': {char: 'К', type: LearningTypes.LETTER},
//     'T': {char: 'Е', type: LearningTypes.LETTER},
//     'Y': {char: 'Н', type: LearningTypes.LETTER},
//     'U': {char: 'Г', type: LearningTypes.LETTER},
//     'I': {char: 'Ш', type: LearningTypes.LETTER},
//     'O': {char: 'Щ', type: LearningTypes.LETTER},
//     'P': {char: 'З', type: LearningTypes.LETTER},
//     '{': {char: 'Х', type: LearningTypes.LETTER},
//     '}': {char: 'Ъ', type: LearningTypes.LETTER},
//     '|': {char: '/', type: LearningTypes.SYMBOL},
//     'A': {char: 'Ф', type: LearningTypes.LETTER},
//     'S': {char: 'Ы', type: LearningTypes.LETTER},
//     'D': {char: 'В', type: LearningTypes.LETTER},
//     'F': {char: 'А', type: LearningTypes.LETTER},
//     'G': {char: 'П', type: LearningTypes.LETTER},
//     'H': {char: 'Р', type: LearningTypes.LETTER},
//     'J': {char: 'О', type: LearningTypes.LETTER},
//     'K': {char: 'Л', type: LearningTypes.LETTER},
//     'L': {char: 'Д', type: LearningTypes.LETTER},
//     ':': {char: 'Ж', type: LearningTypes.LETTER},
//     '"': {char: 'Э', type: LearningTypes.LETTER},
//     'Z': {char: 'Я', type: LearningTypes.LETTER},
//     'X': {char: 'Ч', type: LearningTypes.LETTER},
//     'C': {char: 'С', type: LearningTypes.LETTER},
//     'V': {char: 'М', type: LearningTypes.LETTER},
//     'B': {char: 'И', type: LearningTypes.LETTER},
//     'N': {char: 'Т', type: LearningTypes.LETTER},
//     'M': {char: 'Ь', type: LearningTypes.LETTER},
//     '<': {char: 'Б', type: LearningTypes.LETTER},
//     '>': {char: 'Ю', type: LearningTypes.LETTER},
//     '?': {char: ',', type: LearningTypes.SYMBOL}
//   },
// };

//dfkjskalgeryuwiqoptcvbnxmz[]\;',./1234567890-=
//dfhjskalgeryuwiqoptcvbnxmz[]\;',./1234567890-=
//1234567890-=qwertyuiop[]\asdfghjkl;'zxcvbnm,./
//-=[]\;',./1234567890qwertyuiopasdfghjklzxcvbnm